FCP-28 | implement monitoring droplet's bandwidth
nguyenquangphuc-vn/f0-capstone-project-backend pull request #19
Opened 2022-04-13 11:05 UTC by nguyenquangphuc-vn

2022-04-13 11:41 UTC, phanle11vn commented on src/constants/enums/index.ts
> +}
cần đặt tên file có nghĩa

2022-04-16 13:25 UTC, trgianghuynh1808 requested changes

2022-04-16 13:25 UTC, trgianghuynh1808 commented on src/controllers/do-cloud.controller.ts
> +    @requestBody() dropletBandwidthRequest: IDropletBandwidthPayload,
sao đổi mỗi tên type mà hông đổi lun tên arg em?

2022-04-16 13:25 UTC, trgianghuynh1808 commented on src/services/do-cloud.service.ts
> +import _ from 'lodash';
k dùng lodash như thế này vì đây là em import toàn bộ thư viện lodash vào trong src. mà thư viện lodash rất to.
xem bài này để biết thêm chi tiết
https://topdev.vn/blog/import-lodash-nhu-the-nao-moi-dung/ 
và sử dụng cách thứ 3
ví dụ:
```
import get from "lodash/get"
```

2022-04-16 14:01 UTC, closed without merging